(FLI::DEFINE-PRECOMPILED-FOREIGN-OBJECT-ACCESSOR-FUNCTIONS
 ((COM.WILDORA.DNS-SD::RECORD-REF :NO-ALLOC-P :ERROR :SIZE COMMON-LISP:T)
  (COM.WILDORA.DNS-SD::SERVICE-REF :NO-ALLOC-P :ERROR :SIZE COMMON-LISP:T)))
